### ISSUE TITLE
minification

### ISSUE THREAD

**Issue by rosedo** [gallofeliz/simple-dijs#80] opened 2019-04-15 10:29 UTC
Greetings,

It seems from the outside that we can minify code that uses Di.js.
But then I saw the `_getArgs` method that seems to analyse code.

Could you explain in the readme the precautions to take for minification?

**Comment by gallofeliz** [comment] 2020-02-13 23:07
Hi,

I am discovering messages in repositories ... I've never been notified.

I work for a company and we use simple-dijs for some of our projects, but in my memory all are in node. I didn't notice problems with notification, but what you say sounds logic.

I have not the experience to explain that in the README. I suppose that we have to avoid to use the mangle feature. Do you have some tips for that ?

Regards,

**Comment by rosedo** [comment] 2020-03-03 09:01
Hi. I use uglify-es with the compress option to false and ecma version to 8, but of course this works for me because I target evergreen browsers and recent nodejs versions only.
Since the mangle feature changes names, avoiding things like aFunction.name of aClass.name can fix the problem.

**Comment by gallofeliz** [comment] 2020-03-14 11:14
I can suggest to add an option to disable the names detection. In my company projects we use this detection and I like it, so this is a problem only in your case. Note that some cases are to be fixed (like comments in the function arguments) but it's not your problem.

What do you think about this option ?

Regards,

**Comment by rosedo** [comment] 2020-03-16 21:28
It's been a long time I forgot about this issue. I'm actually using static dependencies... If your solution works I guess the issue is resolved.

**Comment by gallofeliz** [comment] 2020-03-22 12:07
Ok. If the issue is not anymore an issue, I close it.

Regards,

**Closed by gallofeliz** 2020-03-22 12:07 UTC
